import operator

OP_MAP = {
    ">": operator.gt,
    ">=": operator.ge,
    "<": operator.lt,
    "<=": operator.le,
    "!=": operator.ne,
    "==": operator.eq,
}

DEFAULT_SKIP_KEYS = (
    "alleles_all_haplotypes",
    "assembled_haplotypes",
    "del_read_number",
    "directional_links",
    "final_haplotypes",
    "first_copies",
    "flanking_summary",
    "gene_reads",
    "haplotype_details",
    "haplotype_links",
    "het_sites_not_used_in_phasing",
    "heterozygous_sites",
    "highest_total_cn",
    "homozygous_sites",
    "intergenic_depth",
    "last_copies",
    "links_loose",
    "linked_haplotypes",
    "middle_copies",
    "nonunique_supporting_reads",
    "phase_region",
    "phasing_success",
    "pseudo_reads",
    "raw_alleles",
    "read_details",
    "sample_sex",
    "smn1_read_number",
    "smn2_read_number",
    "smn_del78_read_number",
    "sites_for_phasing",
    "unique_supporting_reads",
)
